### ISSUE TITLE
Infinispan not propagating cache

### ISSUE THREAD

**Issue by CalamarBicefalo** [thomasdarimont/keycloak-infini-kube#3]
I am deploying Keycloak in kubernetes using a similar config to the one in this docker image. I get jGroups to form a cluster, but infinispan cannot propagate the initial state, therefore preventing the cluster from becoming healthy.

The cluster uses KUBE_PING
`Setting JGroups discovery to kubernetes.KUBE_PING with properties {port_range=>1}`

The coordinator uses KUBE_PING to form a cluster successfully

```
10:37:50,295 INFO  [org.infinispan.CLUSTER] (thread-9,ejb,keycloak-59c67569f7-wvjmn) ISPN000094: Received new cluster view for channel ejb: [keycloak-59c67569f7-wvjmn|1] (2) [keycloak-59c67569f7-wvjmn, keycloak-59c67569f7-6fdd6]
10:37:50,299 INFO  [org.infinispan.CLUSTER] (thread-9,ejb,keycloak-59c67569f7-wvjmn) ISPN100000: Node keycloak-59c67569f7-6fdd6 joined the cluster
[...]
10:37:52,166 INFO  [org.infinispan.CLUSTER] (remote-thread--p7-t2) [Context=actionTokens] ISPN100002: Starting rebalance with members [keycloak-59c67569f7-wvjmn, keycloak-59c67569f7-6fdd6], phase READ_OLD_WRITE_ALL, topology id 2
[...]
10:37:52,174 INFO  [org.infinispan.CLUSTER] (remote-thread--p7-t8) [Context=work] ISPN100002: Starting rebalance with members [keycloak-59c67569f7-wvjmn, keycloak-59c67569f7-6fdd6], phase READ_OLD_WRITE_ALL, topology id 2
```

The initial cache transfer starts. The coordinator starts getting timeouts:

```
10:38:24,999 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p10-t1) ISPN000136: Error executing command RemoveCommand, writing keys [98c9eca3-80c3-47b6-a3a7-59dc2a7207f1]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 2 from keycloak-59c67569f7-6fdd6
        at org.infinispan.remoting.transport.impl.MultiTargetRequest.onTimeout(MultiTargetRequest.java:167)
        at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:87)
        at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:22)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

10:38:35,036 ERROR [org.infinispan.interceptors.impl.InvocationContextInterceptor] (timeout-thread--p10-t1) ISPN000136: Error executing command PutKeyValueCommand, writing keys [98c9eca3-80c3-47b6-a3a7-59dc2a7207f1]: org.infinispan.util.concurrent.TimeoutException: ISPN000476: Timed out waiting for responses for request 3 from keycloak-59c67569f7-6fdd6
        at org.infinispan.remoting.transport.impl.MultiTargetRequest.onTimeout(MultiTargetRequest.java:167)
        at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:87)
        at org.infinispan.remoting.transport.AbstractRequest.call(AbstractRequest.java:22)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

On the other hand the other node gets stuck on the state transfer until eventually it gives up:

```
10:37:52,033 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 52) WFLYCLINF0002: Started keys cache from keycloak container
10:37:52,034 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 53) WFLYCLINF0002: Started realms cache from keycloak container
10:37:52,036 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 54) WFLYCLINF0002: Started authorization cache from keycloak container
10:37:52,036 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 61) WFLYCLINF0002: Started users cache from keycloak container
//It stagnates here
```

**Comment by chuegel** [comment]
@CalamarBicefalo you have to configure keycloak using TCP instead of UDP

```
<subsystem xmlns="urn:jboss:domain:jgroups:6.0">
            <channels default="ee">
                <channel name="ee" stack="tcp" cluster="ejb"/>
            </channels>
```

Or via configmap in kubernetes:

```
## set cache attributes
/subsystem=infinispan/cache-container=keycloak/distributed-cache=sessions:write-attribute(name=owners, value=${env.CACHE_OWNERS:2})
/subsystem=infinispan/cache-container=keycloak/distributed-cache=authenticationSessions:write-attribute(name=owners, value=${env.CACHE_OWNERS:2})
/subsystem=infinispan/cache-container=keycloak/distributed-cache=offlineSessions:write-attribute(name=owners, value=${env.CACHE_OWNERS:2})
/subsystem=infinispan/cache-container=keycloak/distributed-cache=loginFailures:write-attribute(name=owners, value=${env.CACHE_OWNERS:2})
## set cluster communication to TCP
/subsystem=jgroups/channel=ee:write-attribute(name=stack, value=tcp)
```

**Comment by autarchprinceps** [comment]
We're seeing the same issues. We have it deployed via the Helm Chart, which definitively sets the lower set of options in the configmap.

The only additional thing I noticed, that many, though not all of the timeouts happen during command RemoveExpiredCommand.
